spring.application.name=ogrenciSistem
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://ep-broad-dawn-b2ybhnmr-pooler.c-6.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_cgmSq4UF0RDu&sslmode=require&channelBinding=require